### ISSUE TITLE
answer of Chapter 2 exercises

### ISSUE THREAD

**Issue by lmoyrd** [AllenDowney/ThinkStats2#100]
I'm new of statistics.
And Recently I walked through your book.When I went to the Chapter 2 exercises,I saw:
![image](https://user-images.githubusercontent.com/10935725/37340610-a29b607a-26f9-11e8-9b7b-6b4fd8225e8e.png)
I learned the summary statistics like:  **mean,variance,effect size.**
so the question is    what is the answer and why .
By the way,
![image](https://user-images.githubusercontent.com/10935725/37341405-3b6efdf0-26fc-11e8-957a-ef03b9c50d4d.png)
the Cohen’s d is very small,so what;s the meaning of this result? I can't understand
Thanks a lot !

**Comment by amanrai2508** [comment]
For the first one,the patient will be anxious when it is taking more than normal weeks.Standard deviation can be useful in this type of situation
