### ISSUE TITLE
DiffMeansPermute Limitations

### ISSUE THREAD

**Issue by gmrwvu** [AllenDowney/ThinkStats2#102]
I would like to clarify any distribution limitations for your DiffMeansPermute hypothesis class.  This class computes its own distribution of the test statistic for two groups. So, the two groups can have a uniform, exponential, normal, or Pareto distribution and the resultant p-value would still indicate significance in the difference between the means. Am I understanding this correctly?

**Comment by AllenDowney** [comment]
Yes, permutation tests do not make any distribution assumptions.

**Comment by gmrwvu** [comment]
Thank you.
