### ISSUE TITLE
Chapter 3 exercises #2 solution issue

### ISSUE THREAD

**Issue by burmecia** [AllenDowney/ThinkStats2#104]
In the Chapter 3 exercises No. 3,  the solution is as below:

```Python
hist = thinkstats2.Hist()

for caseid, indices in preg_map.items():
    if len(indices) >= 2:
        pair = preg.loc[indices[0:2]].prglngth
        diff = np.diff(pair)[0]
        hist[diff] += 1
```

This solution seems only compared the 1st baby and the 2nd baby, would it be better to compare 1st baby with all the other babies for an individual woman? My suggestion is as below:

```Python
hist = thinkstats2.Hist()

for case_id, indices in preg_map.items():
    if len(indices) >= 2:
        for i in range(1, len(indices)):
            pair = preg.loc[[indices[0], indices[i]]].prglngth
            diff = np.diff(pair)[0]
            hist[diff] += 1
```

Comments are welcomed. Thanks.

**Comment by AllenDowney** [comment]
Your version uses more data, but it has some non-independence that
complicates things a bit.

**Comment by burmecia** [comment]
Agree. I think my suggestion might be better to answer the question "Are first babies more likely to be late for an individual woman?".

**Comment by stellalgh** [comment]
# hist[diff] += 1
Could someone tell what is the meaning of this line of code? Thanks.

**Comment by burmecia** [comment]
> # hist[diff] += 1
> 
> Could someone tell what is the meaning of this line of code? Thanks.

`hist` is a counter, if keeps number records for each pregnancy length difference. For example, hist[0] saves the number of cases for zero difference between 1st baby and 2nd baby's pregnancy length, that is, 1st baby and 2nd baby pregnancy length is same. So, `dist[diff] += 1` is just to increase that counter when it sees that particular case.
