### ISSUE TITLE
Sampling Weights with DiffMeansPermute?

### ISSUE THREAD

**Issue by gmrwvu** [AllenDowney/ThinkStats2#107]
Is it necessary to consider sampling weights when using the DiffMeansPermute class?  Or, are sampling weights really only a consideration in coefficient calculation such as in linear regression?

**Comment by AllenDowney** [comment]
Yes, it would be better to use sampling weights to resample before each
iteration of the permutation test.  But at this point in the book, we
haven't done weighted resampling yet, right?

**Comment by gmrwvu** [comment]
You are correct. There seems to be several types of weights - one about how many people each person represents, and others like dweights in the European Social Survey.  I have your algorithm for applying the first kind.  The dweights seem to be deceptively simple: just multiple the dweight by the attribute you are analyzing or is there a more complex action to take with them?
