### ISSUE TITLE
Numpy issue

### ISSUE THREAD

**Issue by hashTagKehl** [AllenDowney/ThinkStats2#108]
I'm trying the first test.  This is the error I am getting.  I went to the bumpy page and used the git cmd to install bumpy and configure the data.

Traceback (most recent call last):
  File "/Users/chriskehl/Desktop/nsfg.py", line 11, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by hashTagKehl** [comment]
I'm a newbie also, first time working with any of these platforms.

**Comment by mica5** [comment]
make sure you've done `pip install numpy` (with a lowercase "N") rather than installing bumpy.
I'll second the recommendation made by the book to install anaconda. anaconda comes with a lot of the packages necessary for following along with the book materials: https://www.anaconda.com/download/ that should reduce the number of individual packages that need to be installed afterwards.

**Comment by hashTagKehl** [comment]
Thanks for the comments. I’ve installed through the pip install.  Running this through idle is where I was getting the error.  I’ve installed anaconda, which application should I launch and run the script through.

**Comment by AllenDowney** [comment]
Now that you have Anaconda, I suggest opening the Anaconda prompt and
running the Python programs on the command line.

The Anaconda prompt is just a Command Window set up to have Python on the
search path.

**Comment by hashTagKehl** [comment]
I see the python file, I'm running a MAC is there a particular python file I should chose for the Mac OS?

**Comment by mica5** [comment]
did you try Professor Downey's recommendations first?
> Now that you have Anaconda, I suggest opening the Anaconda prompt and running the Python programs on the command line.
> The Anaconda prompt is just a Command Window set up to have Python on the search path.

**Comment by hashTagKehl** [comment]
I'll try that, thanks.  I'll need to play around with anaconda to find the windows and features.  I'll tackle this again tomorrow.  Thanks all for all the help.

**Comment by hashTagKehl** [comment]
Ok I've worked through this issue.  I was able to open anaconda navigator and use vscode to run the nsfg.py test.   passed.  Thanks for helping me out with this issue.
