### ISSUE TITLE
Chapter 3. Excercise 3.2

### ISSUE THREAD

**Issue by mlsmall** [AllenDowney/ThinkStats2#112]
The exercise states: "Write functions called PmfMean and PmfVar that take a Pmf object and compute the mean and variance"

What is the solution? How do we write these functions?

**Comment by AllenDowney** [comment]
I should have put solutions in chap03soln.ipynb, but it looks like I
didn't.  I'll do that when I have a chance.

In the meantime, check out:
https://github.com/AllenDowney/ThinkStats2/blob/master/code/thinkstats2.py#L546

**Comment by mlsmall** [comment]
Thanks!

**Comment by AllenDowney** [comment]
This should be resolved with bf87d3e
