### ISSUE TITLE
MatplotlibDeprecationWarning prevents run of test_models.py script (Exercise 5-5)

### ISSUE THREAD

**Issue by ijmiller2** [AllenDowney/ThinkStats2#117]
Here's the error I'm getting:

/anaconda2/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
/Users/ijmiller2/Desktop/UW_2018/ThinkStats2/code/thinkplot.py:118: UserWarning: Ran out of colors.  Starting over.
  warnings.warn('Ran out of colors.  Starting over.')

**Comment by AllenDowney** [comment]
Thanks for letting me know.  I'll fix that as soon as I can.

**Comment by ijmiller2** [comment]
Great, thank you!
