### ISSUE TITLE
thinkplot.Show gave error

### ISSUE THREAD

**Issue by mkepke** [AllenDowney/ThinkStats2#121]
I was typing in the commands in chapter 2 and thinkplot.Show(xlabel='value', ylabel='frequency')

gave me the following error

No handles with labels found to put in legend.
![screen shot 2018-09-28 at 9 33 33 am](https://user-images.githubusercontent.com/43621582/46211493-a7a82b80-c301-11e8-8481-7bf3c7765a94.png)

**Comment by AllenDowney** [comment]
That's just a warning, so you can ignore it for now.  I will push a fix as
soon as I can.

I believe you can avoid it by passing `legend=False` to `Show()`.

**Comment by mkepke** [comment]
This is what I get with passing legend=False
(same result with legend=false)
![screen shot 2018-09-28 at 10 45 57 am](https://user-images.githubusercontent.com/43621582/46215582-c0b5da00-c30b-11e8-9dc7-4a4d0e2af8f9.png)

**Comment by mkepke** [comment]
If it helps, I had the same error on Jupyter Notebook chap02ex, but strangely enough the error went away.  This occurs on Spyder Python 3.6

**Comment by AllenDowney** [comment]
Has to be False, not 'False', not false.

**Comment by mkepke** [comment]
Thanks Allen, that removed the error.  Now, to figure out why the data isn't displayed.

**Comment by nps1984** [comment]
@mkepke Did you figure out why data isn't displayed? I'm having the same issue.

**Comment by AllenDowney** [comment]
What development environment are you working in?  I strongly recommend Jupyter.

The thinkplot functions you are using are just thin wrappers around matplotlib functions, so I suspect this is a problem with matplotlib in your environment.

**Comment by nps1984** [comment]
I just figured it out I believe...

If you run (all in one block):
hist = thinkstats2.Hist([1, 2, 2, 3, 5])
thinkplot.Hist(hist)
thinkplot.Show(xlabel='value', ylabel='frequency')

It works like a charm.

If you run (all individually):
hist = thinkstats2.Hist([1, 2, 2, 3, 5]) # enter

Then:
thinkplot.Hist(hist) # enter

Then: 
thinkplot.Show(xlabel='value', ylabel='frequency') #enter

Sorry about the confusion.

**Comment by AllenDowney** [comment]
Glad you worked it out.  What development environment are you using?


On Tue, Jan 15, 2019, at 11:32 AM, nps1984 wrote:
> I just figured it out I believe...


> If you run (all in one block):
>  hist = thinkstats2.Hist([1, 2, 2, 3, 5])
>  thinkplot.Hist(hist)
>  thinkplot.Show(xlabel='value', ylabel='frequency')


> It works like a charm.


> If you run (all individually):
>  hist = thinkstats2.Hist([1, 2, 2, 3, 5]) # enter


> Then:
>  thinkplot.Hist(hist) # enter


> Then:
>  thinkplot.Show(xlabel='value', ylabel='frequency') #enter


> Sorry about the confusion.


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/AllenDowney/ThinkStats2/issues/121#issuecomment-454457665

**Comment by nps1984** [comment]
I was using spyder and typing (or copying/pasting) your code into the console. I then switched to JupyterLab, but was essentially doing the same thing. Executing the code from the console and executing line by line. When I would copy/paste chunks of code into the console and execute the entire chunk, it worked! I'm just getting into python so I'm sure it was misunderstanding on my part.

**Comment by AllenDowney** [comment]
Got it.  I will look for places to warn people about this issue.

Thanks!



On Tue, Jan 15, 2019, at 1:08 PM, nps1984 wrote:
> I was using spyder and typing (or copying/pasting) your code into the
> console. I then switched to JupyterLab, but was essentially doing the
> same thing. Executing the code from the console and executing line by
> line. When I would copy/paste chunks of code into the console and
> execute the entire chunk, it worked! I'm just getting into python so
> I'm sure it was misunderstanding on my part.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/AllenDowney/ThinkStats2/issues/121#issuecomment-454492391
