### ISSUE TITLE
Exercise 3.4

### ISSUE THREAD

**Issue by KeyaVibhakar** [AllenDowney/ThinkStats2#125]

**Comment by KeyaVibhakar** [comment]
Could you please explain, why we multiply diff (which is;  the difference between the runner's speed and observer's speed) with the probability of a given runner's speed; to get the biased data?

`def ObservedPmf(pmf, speed, label=None):

    new = pmf.Copy(label=label)
    for val in new.Values():
        diff = abs(val - speed)
        new.Mult(val, diff)
    new.Normalize()
    return new
`

**Comment by AllenDowney** [comment]
Because the probability of observing any runner is proportional to the difference between their speed and mine.

On Wed, Mar 13, 2019, at 7:48 AM, KeyaVibhakar wrote:
> Could you please explain, why we multiply diff (which is; the difference between the runner's speed and observer's speed) with the probability of a given runner's speed; to get the biased data?

> `def ObservedPmf(pmf, speed, label=None):

> `new = pmf.Copy(label=label)
for val in new.Values():
    diff = abs(val - speed)
    new.Mult(val, diff)
new.Normalize()
return new
`

**Comment by KeyaVibhakar** [comment]
Thank you!
