### ISSUE TITLE
I cannot find codes for ThinkStat2

### ISSUE THREAD

**Issue by YeonjooSmith** [AllenDowney/ThinkStats2#127]
Dear Mr. Downey, 
First of all, thank you so much for providing your book online.
I just started to read the chapter one of your book and while I wanted to run your code,  I could not find your code in your repository.  Is it going to be available soon?

Thanks again, 

Yeonjoo

**Comment by mctopherganesh** [comment]
Hey there @YeonjooSmith 

Were you able to clone the repository to your system locally?

Once you do that, if you navigate to ThinkStats2 > code, all the code to run the examples and do the assignments should be in there.

**Comment by YeonjooSmith** [comment]
Hi @mctopherganesh 
Thank you. I was able to clone the repository and now I can access to codes!

**Comment by AllenDowney** [comment]
Glad to hear it!
