### ISSUE TITLE
Many files missing to build book

### ISSUE THREAD

**Issue by avibrazil** [AllenDowney/ThinkStats2#128]
Under book folder, trying to "make" it, it fails with missing files:

fancyhdr.sty
amsthm.sty
comment.sty

**Comment by tartansandal** [comment]
These are normally part of you TexLive installation. How to get them depends on your platform/distribution. If you are on Ubuntu, I believe installing `texlive-latex-extras` gets you these packages. An alternative is a local user install of TexLive (https://www.tug.org/texlive/quickinstall.html).  With that you can use the `tlmgr` command to install each of those packages.
