### ISSUE TITLE
Codebook server unavailable 

### ISSUE THREAD

**Issue by resonates7** [AllenDowney/ThinkStats2#178]
I'm working through the book. It references the codebook in several places via the below link. But, this link is not available. This server's been down for the last several times I've tried to access it over the span of two weeks or so.

Is there another way to access this information?

http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=FEM&section=R&subSec=7876&srtLabel=607543

![image](https://user-images.githubusercontent.com/49754697/105221236-d677ea80-5b26-11eb-95c2-9abefc5905fc.png)

**Comment by AllenDowney** [comment]
Sadly, that's a permanent change, according to this page: https://www.cdc.gov/nchs/nsfg/nsfg_2015_2017_puf.htm

I will update this link to point to the static PDF.

Thanks for letting me know!
