### ISSUE TITLE
Chapter 13 Solutions def ResampleDivorceCurve 

### ISSUE THREAD

**Issue by resonates7** [AllenDowney/ThinkStats2#185]
The solution for chapter 13 def ResampleDivorceCurve  doesn't work. 

It gives the error 'PlotDivorceCurveByDecade' is not defined. I don't see that defined anywhere in the notebook either.

**Comment by AllenDowney** [comment]
Thanks for letting me know. I will check this out as soon as I can.

**Comment by resonates7** [comment]
I wouldn’t have raised an issue for this alone, but some aspects of this code will be deprecated. I changed the first bit of the notebook from suppressing future warnings to suppress deprecation warnings.

 

I tried to fix it myself, but it seems it’s imbedded deeply in the thinkstats code.

**Comment by AllenDowney** [comment]
This should work as of https://github.com/AllenDowney/ThinkStats2/commit/17edd83e944c607a49cc52a9d023a494ce3c2bfd
