### ISSUE TITLE
the zip file is damaged

### ISSUE THREAD

**Issue by sadek-sh** [AllenDowney/ThinkStats2#187]
when I try to download the code as a zip file I can't extract it and I have an error message that the archive is damaged

**Comment by AllenDowney** [comment]
Which file?

**Comment by sadek-sh** [comment]
![image](https://user-images.githubusercontent.com/81585059/127656303-a96c0860-7d97-43b7-a636-f51ef6d38f85.png)

**Comment by sadek-sh** [comment]
I am sorry if I didn't get it right I am new in using GitHub and I didn't Know if I using it right but I tried to download the code and that it is what happened

**Comment by AllenDowney** [comment]
No problem. That file is generated by GitHub -- I just downloaded it and unzipped it successfully.
Maybe try downloading it again, or using a different application to unzip it? I don't know that WinRAR handles zip files.

https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc
