### ISSUE TITLE
np.int is deprecated as of numpy 1.2

### ISSUE THREAD

**Issue by Scharps** [AllenDowney/ThinkStats2#200]
Error raised:
`AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?`

Changing `np.int` to `int` resolves to issue on line 2818 of thinkstats2.py

**Comment by AllenDowney** [comment]
Right. Looks like there are some references to np.float as well. I'll get that fixed asap. Thanks for letting me know!
