### ISSUE TITLE
Update CDC NSFG Url in chap01ex.ipynb

### ISSUE THREAD

**Issue by optimopium** [AllenDowney/ThinkStats2#204]
The current URL of cycle 6 Codebooks in [chap01ex.ipynb](https://github.com/AllenDowney/ThinkStats2/blob/master/code/chap01ex.ipynb) is wrong. You can update it to [this.](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf)

**Comment by AllenDowney** [comment]
Will fix. Thank you!
