### ISSUE TITLE
Solution is Wrong chap01soln.ipynb

### ISSUE THREAD

**Issue by optimopium** [AllenDowney/ThinkStats2#205]
The solution to the following question in [chap01soln.ipynb](https://github.com/AllenDowney/ThinkStats2/blob/master/solutions/chap01soln.ipynb) is wrong.

**Question:** What was the birthweight of the first baby born to the respondent with caseid `5012`?

**Current Answer:** `preg[preg.caseid==5012].birthwgt_lb`

**But Correct Answer:** `preg.loc[(preg.caseid==2298) & (pregordr==1), "totalwgt_lb"]`

You are not considering the first baby born part of the question in the current solution.

**Comment by AllenDowney** [comment]
Yes, that's better. Thanks!
