### ISSUE TITLE
missing log-log scale in solution for Weibull transform (chap05soln.ipynb)

### ISSUE THREAD

**Issue by rjoberon** [AllenDowney/ThinkStats2#206]
The solution for the exercise in Chapter 5 to create a transformation which shows a straight line for Weibull distributed data is missing the log-log transformation:

```python
sample = [random.weibullvariate(2, 1) for _ in range(1000)]
cdf = thinkstats2.Cdf(sample)
thinkplot.Cdf(cdf, transform="weibull")
thinkplot.Config(xlabel="Weibull variate", ylabel="CCDF")
```
The [last line](https://github.com/AllenDowney/ThinkStats2/blob/master/solutions/chap05soln.ipynb?short_path=fe5b0c5#L2580) should be 
```python
thinkplot.Config(xlabel="Weibull variate", ylabel="CCDF", xscale="log", yscale="log")
```
instead. Then we get a straight line also for other values of k then just k=1.

(This seems to be a bit more complex, since `thinkstats.Cdf` correctly sets `xscale` and `yscale` to "log" but the `scale` return value of `thinkstats.Cdf` is not used here. Another option would be to replace the last two lines with 
```python
scale = thinkplot.Cdf(cdf, transform="weibull")
thinkplot.Config(xlabel="Weibull variate", ylabel="CCDF", xscale=scale["xscale"], yscale=scale["yscale"])
```
but that's less transparent.)

**Comment by AllenDowney** [comment]
Will fix. Thank you!
