### ISSUE TITLE
mismatch between documentation and code in thinkstats2.Jitter

### ISSUE THREAD

**Issue by rjoberon** [AllenDowney/ThinkStats2#207]
The documentation for [Jitter](https://github.com/AllenDowney/ThinkStats2/blob/master/code/thinkstats2.py#L2404) states *Jitters the values by adding a uniform variate in (-jitter, jitter)* but the code does 
```python
np.random.normal(0, jitter, n) + values
```
which is normal distributed data which is not necessarily (rather unlikely) in the range (-jitter, jitter). 

Either the documentation should be changed or the code to
```python
np.random.uniform(-jitter, jitter, n)
```
(which would also better fit the purpose in Ch. 5 to "undo" rounding)

**Comment by AllenDowney** [comment]
Fixed. Thank you!
