### ISSUE TITLE
two tasks in homework 4 seem to be identical

### ISSUE THREAD

**Issue by rjoberon** [AllenDowney/ThinkStats2#208]
In [homework 4](https://github.com/AllenDowney/ThinkStats2/blob/master/homeworks/homework04.ipynb) task 2:

> To see what the relationship between income and education looks like, group the dataset by `educ` and plot mean income at each education level.

is IMHO identical to task 5:

> Use groupby to group respondents by `educ`, then plot mean `realinc` for each education level.

It could be more appropriate to group by `sex` instead (this would fit to the preceding analysis).

**Comment by AllenDowney** [comment]
That is actually as intended -- plotting the data this way is the background we'll compare with the predictions from the model. It's the same background for the two models.

I see why that's confusing though -- I will revise that if I have a chance.
