### ISSUE TITLE
Follow common naming conventions/distinguish classes and functions

### ISSUE THREAD

**Issue by nicktimko** [AllenDowney/ThinkStats2#21]
I get extremely confused when reading your book as it's difficult to tell what's a function and what's a class. [PEP-8][pep8] generally recommends that classes are named with `CapWords` and functions with `lower_case` ("words separated by underscores as necessary to improve readability").  The other common guide, [Google's Python Style Guide][googlestyle], also recommends `CapWords` for classes and `lower_case_with_underscores` for functions.

I'm not advocating that one or the other must be rigidly followed, but at the very least I'd prefer that classes and functions/methods are named *differently*.

[pep8]: https://www.python.org/dev/peps/pep-0008/#prescriptive-naming-conventions
[googlestyle]: https://google-styleguide.googlecode.com/svn/trunk/pyguide.html?showone=Naming#Naming

**Comment by AllenDowney** [comment]
Nick, you are right about the style guides.  My only excuse is that I
developed this library while working at Google and their internal style
guide requires camel caps for function and method names (but not their
external style guide).

At some point I might add aliases so you can refer to functions and methods
using either style.  thinkplot.py already provides this feature.
