### ISSUE TITLE
Update pandas inplace operation

### ISSUE THREAD

**Issue by Etrama** [AllenDowney/ThinkStats2#211]
To make sure the code is future proof (pandas 3 proof), all the pandas operations that mention"inplace=True" need to be updated. At the time I checked, this was 53 results in 20 files:
![image](https://github.com/AllenDowney/ThinkStats2/assets/22076465/b1d27388-9ecd-4244-b28e-cdb3217de46d)

No promises, but I might make a pull request that fixes this.

If you need more evidence: [stackoverflow post](https://stackoverflow.com/questions/45570984/in-pandas-is-inplace-true-considered-harmful-or-not).

**Comment by AllenDowney** [comment]
Thanks for bringing this to my attention, and thanks for the offer to make a PR, but I'll ask you to hold off.

First, a lot of the code in this repo gets generated from other code, so you don't want to modify the ones that get generated.

Second, I am unsure whether I will future-proof this code or not -- I might just pin it to Pandas < 3.0.

Thinking...

**Comment by Etrama** [comment]
Food for thought-
Cons:
- Extra effort: There are also some explanations in the book's text that would need to be updated if the "inplace" operations were updated. 
![image](https://github.com/AllenDowney/ThinkStats2/assets/22076465/9736b28b-ccd1-4a17-bce4-fb45fce846fc)
![image](https://github.com/AllenDowney/ThinkStats2/assets/22076465/76b0931e-17f4-483f-96eb-b72a9b55c20d)

Pros:
- Good python and pandas habits inculcated in people who read the book. If newbies aren't exposed to "inplace", I daresay they will stick to what they know. However, one could also argue that people motivated enough would find this out themselves.

I'll leave the final decision to you.

**Comment by Etrama** [comment]
Thank you!
