### ISSUE TITLE
variable names wrong/misleading in code for Section 8.5

### ISSUE THREAD

**Issue by rjoberon** [AllenDowney/ThinkStats2#212]
In [Section 8.5](https://greenteapress.com/thinkstats2/html/thinkstats2009.html#sec86#sec85) we try to estimate the parameter $\lambda$ of an exponential distribution using the sample mean and median. The [corresponding description and code in the notebook](https://github.com/AllenDowney/ThinkStats2/blob/master/code/chap08ex.ipynb?short_path=c1a2bfd#L304) should be changed:

> The following function simulates experiments where we try to estimate the mean of an exponential distribution using the mean and median of a sample.  

should be 

> The following function simulates experiments where we try to estimate the parameter $\lambda$ of an exponential distribution using the mean and median of a sample. 

and the variables `means` and `medians` in the code should be `Ls` and `Lms`.

**Comment by AllenDowney** [comment]
Yes, that's better. Thanks!
