### ISSUE TITLE
bug in 8.7 Glossary - bias (of an estimator): 

### ISSUE THREAD

**Issue by ToshiKurokawa** [AllenDowney/ThinkStats2#24]
The current (2.0.27) definition of bias (of an estimator): 
The tendency of an estimator to be above or below the actual value of the parameter, when averaged over repeated experiments.
should be read as 
The tendency of estimates by an estimator to be above or below the actual value of the parameter, when averaged over repeated experiments.

**Comment by AllenDowney** [comment]
Yes, quite right.  I will change it to:

The tendency an estimator to produce estimates above or below the actual
value of the parameter, when averaged over repeated experiments.

Thanks!
Allen
