### ISSUE TITLE
Cannot Run Code

### ISSUE THREAD

**Issue by loffelmacher** [AllenDowney/ThinkStats2#37]
I suppose that it's something I'm doing wrong, but anytime I try to run the code from my Mac OSX terminal I'm getting the following error:

./nsfg2.py: line 16: syntax error near unexpected token `('
./nsfg2.py: line 16: `def MakeFrames():'

This happens right from the start, when I try to run `./nsfg2.py`. I did install Anaconda and try to run my code through there, no dice. Could not figure out how to actually *run* a .py file from Anaconda.

So then I did some `pip install`s for the packages called-out in the book, I installed pandas, numpy, scipy, statsmodela, and matplotlib. Still getting this error message.

**Comment by AllenDowney** [comment]
nsfg2.py is not executable.  Try

python nsfg.py

You might want to start with Think Python.

**Comment by loffelmacher** [comment]
That was such a beginner mistake, I apologize! However I tried as suggested now I bump into the warning below. Also I am on Python 2.7.9.

nsfg2.py:57: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df.birthwgt_lb1[df.birthwgt_lb1 > 20] = np.nan

**Comment by AllenDowney** [comment]
You can ignore that warning, but I will make a note to rewrite this to
avoid the warning or suppress it.

**Comment by loffelmacher** [comment]
thanks for your help and this wonderful book!

**Comment by yongduek** [comment]
The warning will disappear by replacing the line 
    `df.birthwgt_lb1[df.birthwgt_lb1 > 20] = np.nan`
by
    `df.loc[df.birthwgt_lb1 > 20, 'birthwgt_lb1'] = np.nan`

cf.: [How to deal with SettingWithCopyWarning in Pandas?](https://stackoverflow.com/questions/20625582/how-to-deal-with-settingwithcopywarning-in-pandas)

**Comment by AllenDowney** [comment]
This is now resolved with 2cfbdb0816be027dab9495ac152faecab7f1dc3e

(thanks to your PR)
