### ISSUE TITLE
Use hyperref package for pdf metadata (TOC, Title, Author)

### ISSUE THREAD

**Issue by tobanw** [AllenDowney/ThinkStats2#38]
It would be nice to have a "document outline" (I would call it a metadata TOC) for using the navigation tree in pdf viewers (usually you can toggle between thumbnail view and document outline). This can easily be added by using the [`hyperref` package](https://en.wikibooks.org/wiki/LaTeX/Hyperlinks) -- by default it generates the document outline and you can specify more metadata. For example:

``` latex
\usepackage{hyperref}

\hypersetup{
    pdftitle={Think Stats}
    pdfauthor={Allen B. Downey}
}
```

It will also automatically linkify all your references! From the link above:
_"This will automatically turn all your internal references into hyperlinks. It won't affect the way to write your documents: just keep on using the standard \label-\ref system (discussed in the chapter on Labels and Cross-referencing); with hyperref those "connections" will become links and you will be able to click on them to be redirected to the right page. Moreover the table of contents, list of figures/tables and index will be made of hyperlinks, too."_

**Comment by AllenDowney** [comment]
Can't get it to work with hevea.

**Comment by tobanw** [comment]
Ah that's too bad. I'll go ahead and close this then.

**Comment by tobanw** [comment]
I just happened upon a method which might get around your problem with hevea. As you can see in [this example](https://en.wikibooks.org/wiki/LaTeX/Modular_Documents#The_main_document_document.tex), you can use the package `ifpdf` to only load `hyperref` when compiling to pdf.
