### ISSUE TITLE
chap01ex - quibble with the prglngth and agepreg exercises

### ISSUE THREAD

**Issue by robin-norwood** [AllenDowney/ThinkStats2#52]
For the exercises:

`Print value counts for prglngth and compare to results published in the codebook` and `Print value counts for agepreg and compare to results published in the codebook.`.

I didn't like that you can't directly compare the results of the code with the data given in those links. My solution was:

```
idxes = ((0, 14), (14, 27), (27, -1))
for i in idxes:
    print(df['prglngth'].value_counts().sort_index()[i[0]:i[1]].sum())
print(df['prglngth'].value_counts().sum())
```

With the results:

```
3522
793
9276
13593
```

Although there may be more elegant/numpy-thonic ways of doing that.

**Comment by AllenDowney** [comment]
I'm not sure I understand.  Is this checking that the value counts add up
to the right total?  That would make them internally consistent, but the
reason for checking the codebook is to make sure they are consistent with
the analysis done by the NSFG folks.

I think I'm missing your point -- sorry!

**Comment by robin-norwood** [comment]
I probably didn't make my point clear enough. Where the chap 1 ipython notebook exercise says

`Print value counts for prglngth and compare to results published in the [codebook](http://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=PREG&section=A&subSec=8016&srtLabel=611931)`

I followed the URL, and expected to write code that reproduced the table shown there. The chap01soln.ipynb instead shows the values week by week:

```
In [3]: df.prglngth.value_counts(sort=False)
Out [3]:
0       15
1        9
2       78
3      151
4      412
...
```

Hence my code above, which matches the table from the codebook.
