### ISSUE TITLE
cannot open chap01ex.ipynb

### ISSUE THREAD

**Issue by wyz33** [AllenDowney/ThinkStats2#53]
Cannot open the chapter 1 ipython notebook exercises, both the problem and the solution files. I get the following error message 
"Unreadable Notebook: /Users/Home/git/ThinkStats2/code/chap01ex.ipynb NotJSONError('Notebook does not appear to be JSON: u\'\n\n\n\n<!DOCTYPE html>\n<html lang="e...',)"

I upgraded my ipython to  version 4.2.1 and it didn't resolve the problem

**Comment by AllenDowney** [comment]
The GitHub renderer seems to have no problem with it:

https://github.com/AllenDowney/ThinkStats2/blob/master/code/chap01ex.ipynb

I wonder if the copy you have locally is not the same as what's in the repo?

Try downloading or cloning a fresh copy?

Allen
