### ISSUE TITLE
Request Allen Downey's permission to port ReadStataDct to pandas.

### ISSUE THREAD

**Issue by owenmk** [AllenDowney/ThinkStats2#57]
Hello Allen Downey,

May I port the ReadStataDct function and parts of class FixedWidthVariables into pandas?
It is outside GPL to do this and I think your permission is sufficient.

Kind regards,

Owen Kelly

**Comment by AllenDowney** [comment]
Yes, I officially license that code to you under the GPL.

ReadStataDct is very hacky and only parses some of the information in the
DCT file, so there is definitely room for improvement!

Allen
