### ISSUE TITLE
TypeError: main() takes exactly 1 argument

### ISSUE THREAD

**Issue by iBadawi** [AllenDowney/ThinkStats2#61]
Hi Allen,

Thanks for the book & code.  I just started working on the code & got this error message when I run the nsfg.py code: 

TypeError                                 Traceback (most recent call last)
<ipython-input-29-abda39cd9364> in <module>()
    165 
    166 if __name__ == '__main__':
--> 167     main(*sys.argv)

TypeError: main() takes exactly 1 argument (3 given)

Can you please explain the issue here and how to fix it? I'm new to Python and spent some time researching this issue but couldn't sort it out.

Thanks

**Comment by AllenDowney** [comment]
If you provide command-line arguments, that would cause the error you are
seeing.  Are you providing command-line arguments?

**Comment by AllenDowney** [comment]
I just pushed a change that will avoid this problem.

**Comment by iBadawi** [comment]
Thank you so much for your prompt response, I tried the new code and it's working fine.
