### ISSUE TITLE
Error in chap03ex.ipynb

### ISSUE THREAD

**Issue by shinigamiryuk** [AllenDowney/ThinkStats2#63]
Hi, I noticed that in 7th cell when we are plotting the pmf, pmf instance should be updated in 6th cell. Not the hist instance. 

    n = hist.Total()
    pmf = hist.Copy()
    for x, freq in hist.Items():
        pmf[x] = freq / n

**Comment by AllenDowney** [comment]
Good catch!  That should be fixed now.  Thanks!

On Tue, Feb 21, 2017 at 11:05 AM, Khirod Kant Naik <notifications@github.com
