### ISSUE TITLE
Nitpick with solution for Chapter 3, Exercise 3

### ISSUE THREAD

**Issue by sebastianiorga** [AllenDowney/ThinkStats2#64]
The solution offered in `chap03soln` actually computes the length difference between the 1st birth and the 2nd, as opposed 1st vs all others. 

Code below computes difference between 1st birth prglngth and mean of other births' prglngth. The results are extremely similar but hey.

```python
hist = thinkstats2.Hist()

livePreg = preg[preg.outcome == 1]
livePregMap = nsfg.MakePregMap(livePreg)

for caseid, indices in livePregMap.items():
    if len(indices) >= 2:
        ownLivePregs = livePreg.loc[indices]
        
        firstValue = ownLivePregs.iloc[0].prglngth # assumption: ownLivePregs default sort is same as sorting ascending by birthordr
        others = ownLivePregs.iloc[1:]
        othersMean = others.prglngth.mean()
        
        diff = othersMean - firstValue # same as np.diff([firstValue, othersMean])[0]

        hist[int(diff)] += 1
```

Thanks for the book and the code examples! Very enjoyable so far :)

**Comment by kdedev** [comment]
I was thinking the same thing. Glad to know there are others who thought the same.
I think the ideal solution with would be creating separate pairs of 1st birth and 2nd birth, 1st birth and 3rd birth, 1st birth and 4th birth and so on, instead of single pair of 1st birth and mean of other births.
