### ISSUE TITLE
How to install thinkstats2 in anaconda python

### ISSUE THREAD

**Issue by ba4ekiko1** [AllenDowney/ThinkStats2#66]
Hi, this is probably a silly question but how can i install thinkstats2 package. I am going trough your videos on safaribooks and trying to replicate the notebooks but can't seem to be able to install the package. Trying:

conda install [thinkstats2]
and get:
Package not found: " Package missing in current win-64 channels
I couldn't install it with pip either

Thank you

**Comment by AllenDowney** [comment]
thinkstats2 is not installable as a package.  There are two ways I suggest working with the code:

1) Clone the whole repository and work in the directory that contains the code,

2) Install the thinkx package, which contains modules for all of my books.

Hope that helps!
