### ISSUE TITLE
Python 3 incompatibility in the "pandas_demos.ipynb"

### ISSUE THREAD

**Issue by hisakato** [AllenDowney/ThinkStats2#68]
Please search the file for a code fragment "for sex, weights in d.iteritems():"

With Python 2:
<img width="565" alt="2017-05-05 10 07 41" src="https://cloud.githubusercontent.com/assets/5201469/25772498/5fd313a6-32a7-11e7-97f6-93d400704195.png">

With Python 3:
<img width="622" alt="2017-05-05 10 20 01" src="https://cloud.githubusercontent.com/assets/5201469/25772500/69c0dbf0-32a7-11e7-812b-ca73efb17665.png">

**Comment by gbremer** [comment]
Just created a fix and sent a pull request for this via issue #85
