### ISSUE TITLE
Typo in Dungeons.py

### ISSUE THREAD

**Issue by javabean68** [AllenDowney/ThinkStats2#73]
Hallo Allen,

I love your books! :-) I think here (line 106) should read 'Max' instead of 'Sum':

``thinkplot.Save(root='dungeons2',
                   xlabel=**'Max** of three d6',
                   ylabel='Probability',
                   axis=[2, 19, 0, 0.23],
                   formats=FORMATS,
                   legend=False)

Bye
Fabio

**Comment by AllenDowney** [comment]
That's actually in Think Bayes, not Think Stats, but I found it and fixed
it.  Thanks!
