### ISSUE TITLE
Provide support for Python 3

### ISSUE THREAD

**Issue by gbremer** [AllenDowney/ThinkStats2#76]
The ThinkStats2 code base is not Python 3 compliant, borne out by a quick grep on the code and looking for print statements. A quick improvement and win would be to run futurize on the Python to knock out the low hanging fruit, and after that review the notebooks for similar sorts of code. There is at least one issue that refers to a Python 3 incompatibility in notebook code.

Since Python 2 is not end-of-life, the fixes should not port the code to Python 3 but ensure the code is compatible between Python 2 and Python 3 for next few years.

**Comment by AllenDowney** [comment]
I believe that all code that is used in the book or referred is Python 3 compliant.

There might be some older code lurking in the repo.  I will update it when I have a chance, but it might be low priority.
