### ISSUE TITLE
Error in nsfg.py at line 98 for item() 

### ISSUE THREAD

**Issue by anmolgupta** [AllenDowney/ThinkStats2#83]
First of all, I would like to thank you for such a lovely tutorial. 
I found an error at line 98 in nsfg.py that item() function is not there. Do I need to use compulsary use Python3 as your git repo says? 
It may sounds silly but I am a newbee on this

**Comment by gbremer** [comment]
On behalf of the owner, thank you for the issue report. What is the exception and stacktrace of the error and how did you get there?

**Comment by anmolgupta** [comment]
This is the stack trace:

`Traceback (most recent call last):
  File "/Users/anmol/ThinkStats2/code/nsfg.py", line 165, in <module>
    main()
  File "/Users/anmol/notebook/ThinkStats2/code/nsfg.py", line 158, in main
    assert(ValidatePregnum(resp, preg))
  File "/Users/anmol/notebook/ThinkStats2/code/nsfg.py", line 98, in ValidatePregnum
    for index, pregnum in resp.pregnum.items():
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 3077, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'items'`

I am on python 2.7.12 and pandas version is 0.20.3

**Comment by gbremer** [comment]
This looks like an issue that #79 described. I am suspecting that something changed in pandas, that the items() method has been removed, but have not looked at older versions yet to confirm that guess. An immediate fix for you is to change that items() method call to iteritems() and move on. You can wait for a proper fix -- I have been sticking my nose in here recently, and will get to it -- or you can make the fix and submit a pull request to AllenDowney for review.

**Comment by anmolgupta** [comment]
Thanks for your immediate reply. Changing to iteritems() works.

**Comment by AllenDowney** [comment]
This one it my fault.  I was trying to clean up Python 2/3
incompatibilities and I introduced this error.  I'll fix it right now.

Allen

**Comment by AllenDowney** [comment]
Done 19c22ed6f36adb27ebb2497db53ea460945b7cb5

**Comment by TanwarAbhishek** [comment]
I am facing this issue while running nsfg.py file in anaconda prompt(anaconda3)
i am having this file on desktop already 
please suggest a solution

SyntaxError: invalid syntax

(base) C:\Users\abhis\Desktop>nsfg
  File "C:\Users\abhis\Desktop\nsfg.py", line 7
    <!DOCTYPE html>
    ^

**Comment by AllenDowney** [comment]
You should be able to run it on the command line like this:

```
python nsfg.py
```

But I suggest you don't. I recommend you use the Jupyter notebooks.

Allen
