### ISSUE TITLE
Proposed feature -- Travis CI build for tests, style checks, pdf generation

### ISSUE THREAD

**Issue by gbremer** [AllenDowney/ThinkStats2#88]
Here's something to consider for the project -- a CI build to run the tests nightly, run style checks, check your pdf build. The magic ingredient is a .travis.yml file in the root of the repository that scripts up an environment setup and build commands. It may be useful, it may not.

https://travis-ci.org/gbremer/ThinkStats2

The tests are failing because they want to display matplotlib plots -- that can be accounted for or fixed if this is considered useful.

**Comment by AllenDowney** [comment]
Yes, this is a level of software engineering practice I aspire to!
