### ISSUE TITLE
Import Error: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by diegoquintanav** [AllenDowney/ThinkStats2#92]
Hi. I've just forked the repo and tried to run the first code, ```nsfg.py```. I get an error regarding something with matplotlib.

My intuition tells me that this may have alreade a solution, but I have found none. The full trace of the error is the following

```
diego@ubuntu:~/Documents/dev/ThinkStats2/code$ python nsfg.py 
Traceback (most recent call last):
  File "nsfg.py", line 12, in <module>
    import thinkstats2
  File "/home/diego/Documents/dev/ThinkStats2/code/thinkstats2.py", line 34, in <module>
    import thinkplot
  File "/home/diego/Documents/dev/ThinkStats2/code/thinkplot.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/home/diego/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/diego/anaconda3/lib/python3.5/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "/home/diego/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 15, in <module>
    from .transforms import (Bbox, IdentityTransform, TransformedBbox,
  File "/home/diego/anaconda3/lib/python3.5/site-packages/matplotlib/transforms.py", line 39, in <module>
    from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
ImportError: /home/diego/anaconda3/lib/python3.5/site-packages/matplotlib/../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/diego/anaconda3/lib/python3.5/site-packages/matplotlib/_path.cpython-35m-x86_64-linux-gnu.so)
```

If it means something, I'm using
matplotlib (2.0.2)
Python 3.5.4 :: Anaconda, Inc.
conda 4.3.30
gcc (GCC) 4.8.5

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Thanks

**Comment by diegoquintanav** [comment]
I managed to find a solution. It seems that a newer version of ```gcc``` is required, in particular one that contains ```CXXABI_1.3.9```

After some reading, there are two possible solutions: 
1.  One for the people without anaconda, that is somehow explained [here](http://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths). 

2.  In my case I use Anaconda, and the problem is solved running ```conda install libgcc```, which upgrades the current gcc compiler.

More info about this can be found [here](https://github.com/ContinuumIO/anaconda-issues/issues/483#issuecomment-269135787)

**Comment by AllenDowney** [comment]
I am surprised that that was necessary, but I am glad you resolved the
problem.

Regards,
Allen

**Comment by AllenDowney** [comment]
It looks like the line that's failing is

```
    import matplotlib.pyplot as plt
```

Which means that there is something wrong with your installation of
matplotlib.

Try starting Python and running just that line:

```
$ python
>>> import matplotlib.pyplot as plt
```

If it fails there, then nsfg.py is not the problem.

**Comment by Orientier7** [comment]
I solve this problem by pip uninstalling/reinstalling scipy

**Comment by Saleh-Gholam-Zadeh** [comment]
Typing 

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/diego/anaconda3/lib/

in the terminal will solve the problem

**Comment by CharlieZhaoyl** [comment]
> Typing
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/diego/anaconda3/lib/
> 
> in the terminal will solve the problem

Thanks! This works for me.

**Comment by LetsGoFir** [comment]
> Typing
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/diego/anaconda3/lib/
> 
> in the terminal will solve the problem

works for me too

**Comment by sysu-zjw** [comment]
> Typing
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/diego/anaconda3/lib/
> 
> in the terminal will solve the problem

works for me too :)

**Comment by euna-cho** [comment]
> I managed to find a solution. It seems that a newer version of `gcc` is required, in particular one that contains `CXXABI_1.3.9`
> 
> After some reading, there are two possible solutions:
> 
> 1. One for the people without anaconda, which is somehow explained [here](http://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths).
> 2. In my case I use Anaconda, and the problem is solved with  `conda install libgcc`, which upgrades the current gcc compiler.
> 
> More info about this can be found [here](https://github.com/ContinuumIO/anaconda-issues/issues/483#issuecomment-269135787)

I faced error : `libstdc++.so.6: version `CXXABI_1.3.9' not found`
but `conda install libgcc` worked for me! thanks

**Comment by brando90** [comment]
> conda install libgcc

that didn't work for me

**Comment by soodeh-nilforoushan** [comment]
> export LD_LIBRARY_PATH

Thanks, Work for me

**Comment by k-aleksandrovich** [comment]
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/diego/anaconda3/lib/
> 
> in the terminal will solve the problem

O thank you so much, man
I've almost lost my hope
