### ISSUE TITLE
No module named 'nsfg'

### ISSUE THREAD

**Issue by SheebanWasi** [AllenDowney/ThinkStats2#99]
Hey I ran the nsfg.py in ATOM and it gave me an output as All test Passed, but when I open the ch01.ipynb in notebook and run the very first line it gives me an error 

ModuleNotFoundError: No module named 'nsfg'

I am stuck. ThankYou !

**Comment by AllenDowney** [comment]
In order for Python to find this module, you either need to run the program
with nsfg.py in the current directory or add the directory that contains
nsfg.py to Python's search path.

https://stackoverflow.com/questions/3144089/expand-python-search-path-to-other-source

**Comment by nsdeo12** [comment]
Worked after running inside the **_ThinkStats2\code_** folder.
